---
version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dachereukho
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"